# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d0c45f9e78d5b2cb7fdc53c6342ed2f2b778fb4b3b1450ef72308c63819c4227c3011900eee35fae3018cd9d2a4c90a7dcd6753da871d521cfea181f0bf41ea

test:
  secret_key_base: 196d4a49c8ae8a5400275e21d5f2a19b4cf52425680c3302fdd78ed65141e2a39e04c26898e61f5455d037ff7678e97883a3fd1eeaa5d62427854b994b90aa83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
